// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uderujriuwbzopwhlxde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkZXJ1anJpdXdiem9wd2hseGRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MDU3NjYsImV4cCI6MjA2MjE4MTc2Nn0.gleap1hFtCGv074Q5y0_j_VUAGBP0WERdDCPUP64vuA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);